# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vibeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vibeGUI(object):
    def setupUi(self, vibeGUI):
        vibeGUI.setObjectName("vibeGUI")
        vibeGUI.resize(1362, 944)
        self.centralwidget = QtWidgets.QWidget(vibeGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -30, 1381, 971))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/ravir/OneDrive/Pictures/aiifront/ai.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1120, 900, 111, 31))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1240, 900, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        vibeGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(vibeGUI)
        QtCore.QMetaObject.connectSlotsByName(vibeGUI)

    def retranslateUi(self, vibeGUI):
        _translate = QtCore.QCoreApplication.translate
        vibeGUI.setWindowTitle(_translate("vibeGUI", "MainWindow"))
        self.pushButton.setText(_translate("vibeGUI", "Run"))
        self.pushButton_2.setText(_translate("vibeGUI", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vibeGUI = QtWidgets.QMainWindow()
    ui = Ui_vibeGUI()
    ui.setupUi(vibeGUI)
    vibeGUI.show()
    sys.exit(app.exec_())
